### ISSUE TITLE
Can't open oven beyond peek on mobile

### ISSUE THREAD

**Issue by Leia286** [fernjager/game-off-2013#17]
I'm playing on iPad, and can't open the door to take turkey out.

**Comment by fernjager** [comment]
Thanks for letting us know! Does dragging on the handle of the oven door
work?

Tapping it first should open it up a bit, after which dragging the handle
down should open it up all the way to take the turkey out.

**Comment by Leia286** [comment]
Your suggestion didn't really work.
![37ED4F64-750A-4AFC-B416-CB140B5E6F53](https://user-images.githubusercontent.com/85947805/136665361-09d44a4f-41be-4a7a-9485-d960807424f6.jpeg)

**Comment by fernjager** [comment]
This issue has now been resolved, thanks again for the report!
